export const FIELD_CATALOG = [
  {
    key: "phone",
    label: "Phone Number",
    placeholder: "Enter your phone number",
    type: "tel",
    required: false,
    options: [],
  },
  {
    key: "jobTitle",
    label: "Job Title",
    placeholder: "Enter your job title",
    type: "text",
    required: false,
    options: [],
  },
  {
    key: "industry",
    label: "Industry",
    placeholder: "Select your industry",
    type: "select",
    required: false,
    options: [
      "Real Estate",
      "SaaS / Technology",
      "Healthcare / Medical",
      "E-commerce / Retail",
      "Insurance",
      "Financial Services",
      "Manufacturing",
      "Professional Services",
      "Education",
      "Other",
    ],
  },
  {
    key: "companySize",
    label: "Company Size",
    placeholder: "Select company size",
    type: "select",
    required: false,
    options: [
      "1-10 employees",
      "11-50 employees",
      "51-200 employees",
      "201-500 employees",
      "500+ employees",
    ],
  },
  {
    key: "budget",
    label: "Budget Range",
    placeholder: "Select your budget",
    type: "select",
    required: false,
    options: [
      "Under $1,000/mo",
      "$1,000 - $5,000/mo",
      "$5,000 - $10,000/mo",
      "$10,000+/mo",
      "Not sure yet",
    ],
  },
  {
    key: "website",
    label: "Website",
    placeholder: "Enter your website URL",
    type: "text",
    required: false,
    options: [],
  },
  {
    key: "referralSource",
    label: "How Did You Hear About Us?",
    placeholder: "Select an option",
    type: "select",
    required: false,
    options: [
      "Google Search",
      "Social Media",
      "Referral",
      "Blog / Article",
      "Event / Conference",
      "Other",
    ],
  },
];
